services:
  - type: web
    name: cgpa-fetcher-backend
    env: node
    rootDir: backend
    buildCommand: npm install && apt-get update -y && apt-get install -y chromium
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    autoDeploy: true
